### ISSUE TITLE
Generate strongly-typed IEnumberables for modular content restricted to one type

### ISSUE THREAD

**Issue by kentico-ericd** [Kentico/cloud-generators-net#15]
I'm submitting this for a KC customer (https://app.intercom.io/a/apps/e42kus8l/respond/inbox/all/conversations/9279070347).

If a content type's modular content field is restricted to **exactly one** content type, it would be helpful if the code generator returned a strongly-typed object of that type. ie- instead of:

`public IEnumerable<object> ModularContent { get; set; }`

generate

`public IEnumerable<MyContentType> ModularContent { get; set; }`

I understand this could cause issues if the modular content was modified to allow multiple types, but the code wasn't updated to reflect this.

**Comment by petrsvihlik** [comment]
Unfortunately, there is now way of telling which types may be stored in a modular content element by the time of generation.

If you don't want your changes to be lost during model regeneration, I'd recommend extending the generated class with a partial class:


```csharp
    public partial class MyModel
    {
       // either
        public IEnumerable<MyContentType>MyContentItems => ModularContent.Cast<MyContentType>();

        // or
        [JsonProperty("modular_content")]
        public IEnumerable<MyContentType> MyContentItems { get; set; }
    }
```

See more details on extending generated classes in our [forums](https://forums.kenticocloud.com/discussion/32/strong-types-explained-usage/) and in the [documentation](https://github.com/Kentico/delivery-sdk-net/wiki/Working-with-Strongly-Typed-Models-(aka-Code-First-Approach)).
