### ISSUE TITLE
Default withtypeprovider to true

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-generators-net#19]
What do you think about making the `withtypeprovider` parameter default to `true`?

**Comment by petrsvihlik** [comment]
Let's implement it then!

**Comment by kzisme** [comment]
Hey @petrsvihlik is this a large change?  I've began looking through some of the other issues just to get an idea of what is going on exactly.

**Comment by petrsvihlik** [comment]
hi @kzisme , not really. it should be a matter of adjusting this line: https://github.com/Kentico/cloud-generators-net/blob/master/src/CloudModelGenerator/Program.cs#L20

The expected output is that when you launch the program without explicitly specifying `withtypeprovider` it should generate the class even so.

**Comment by petrsvihlik** [comment]
implemented as a part of https://github.com/Kentico/cloud-generators-net/pull/33
