### ISSUE TITLE
Include ".Generated" in the file names?

### ISSUE THREAD

**Issue by ChristopherJennings** [Kentico/cloud-generators-net#20]
As these are partials and like to be added to, it would make sense to include ".generated" in the file name so that the custom additions to the partial class can have the "core" class name. For example, MyClass.Generated.cs". 

Since I can see this being something that not everyone wants, maybe this could be exposed as an option flag?

**Comment by petrsvihlik** [comment]
It makes sense to me. So far, we've been recommending naming the additional partial classes `***Partial.cs`. What you're proposing is much better. 
To maintain backwards compatibility it should be definitely exposed as a flag which would be turned off by default.
I'd also name it in a generic way "--transformfilenames" (or similar) with a default transformation being the ".Generated" suffix. 
We could introduce another option for adjusting the transformation if the default suffix wouldn't suffice.

**Comment by ChristopherJennings** [comment]
I don't disagree with backwards compatibility, but this is getting more and more complicated to use with a ton of extra flags to add. 

This is obviously a topic for another issue, but I'm wondering if it would make sense to allow all these flags to be set via a config of some kind in order to allow people to more easily save the options they want. I've opened a new issue with this suggestion (#22).

**Comment by petrsvihlik** [comment]
agreed

**Comment by hades200082** [comment]
Further to this, if you're going to generate a *.Generated.cs then you should generate the empty *.cs partial class to go with it if one doesn't already exist.

**Comment by hades200082** [comment]
I've added a pull-request to address the main request here.  My comment above could be considered an enhancement later if required.

**Comment by petrsvihlik** [comment]
thanks @hades200082 ! it's merged now
