### ISSUE TITLE
Default location to some subfolder

### ISSUE THREAD

**Issue by ChristopherJennings** [Kentico/cloud-generators-net#21]
Rather than have it dump all the files in the directory the executable is in, it would be better to dump them into a subfolder based on the project GUID or something (e.g., "Generated_For_00000000-0000-0000-0000-000000000000").

**Comment by petrsvihlik** [comment]
isn't the `[--outputdir "<output-directory>"]` parameter sufficient?

**Comment by ChristopherJennings** [comment]
Yes, that can handle the situation, but similar to #19, I think it would be better to have a smarter default. I have inadvertently forgotten to include this parameter a number of times and it is a pain to clean up the directory after making that mistake.

**Comment by petrsvihlik** [comment]
Ok, it makes sense to me but let's wait for some more feedback on this.

**Comment by ChristopherJennings** [comment]
This would largely be "obsolete" if #22 is implemented.

**Comment by petrsvihlik** [comment]
#22 is implemented. do we want to change the defaults in appSettings.json?

**Comment by JanLenoch** [comment]
Addressed in https://github.com/Kentico/cloud-generators-net/pull/60 .
