### ISSUE TITLE
Allow flag defaults to be configured via config file

### ISSUE THREAD

**Issue by ChristopherJennings** [Kentico/cloud-generators-net#22]
I think it would make sense to allow all these flags to be set via a config of some kind in order to allow people to more easily save the options they want. This would not replace the current flags, but would allow people to configure the default values they want to make running the command easier.

**Comment by MajorGrits** [comment]
#32 

Here is a pull request that I feel handles this or at least is a good starting point. Would love some feedback/suggestion!

**Comment by petrsvihlik** [comment]
implemented by @MajorGrits in #33
