### ISSUE TITLE
Generate empty partial classes

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-generators-net#31]
The utility could generate empty partial classes for customization by developer. The classes would be generated only if the files didn't exist before (so it wouldn't override the customizations).

As always, it should be made optional via a command line parameter.

**Comment by kashifsoofi** [comment]
Do you prefer switch name? Would -gp|--generatepartials work?
And how would you go about naming the files, if this option is set should fileNameSuffix default to .Generated?

**Comment by petrsvihlik** [comment]
hi @kashifsoofi 
- `-gp|--generatepartials` is fine
- the file names should be:
  - MyClass.cs for the empty partial
  - MyClass.Generated.cs for what's being generated now (the model class)...if not set differently by the `filenamesuffix`
- the empty partials should not be overwritten if they already exist (they're meant to be customized by developers)

**Comment by petrsvihlik** [comment]
implemented in #35
