### ISSUE TITLE
Content Type Snippets generate incorrect property names

### ISSUE THREAD

**Issue by hades200082** [Kentico/cloud-generators-net#43]
**Example**

 I have a content type snippet called "Meta Data" with elements "Description" and "Title"

When the generator runs it creates the following properties on the generated models:

```cs
        public const string TitleCodename = "meta_data__title";
        public const string DescriptionCodename = "meta_data__description";
        public string MetaDataPageTitle { get; set; }
        public string MetaDataDescription { get; set; }
```

The problem is with the "code name" properties... their property names should also be prefixed. Otherwise if I had multiple snippets with a "Description" or "Title" field the property names will conflict.

**Comment by JanLenoch** [comment]
Fixed by #59 .
