### ISSUE TITLE
Migrate to System.CommandLine

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-generators-net#46]
Microsoft.Extensions.CommandLineUtils is no longer being maintained by MS and was forked to: https://github.com/natemcmaster/CommandLineUtils

From the long-term perspective, it might make sense to migrate to a standard .net command-line parser:

https://github.com/dotnet/corefxlab/tree/master/src/System.CommandLine

Could help solve #45

**Comment by brunotag** [comment]
Hey keen to pick this up, just one thing: System.CommandLine is currently in pre-release, are you sure you wanna use it?

https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.CommandLine

**Comment by petrsvihlik** [comment]
Hi @brunotag 
No, I haven't noticed that. Do we know when it's gonna be RTMed?

**Comment by JanLenoch** [comment]
Fixed by #56
