### ISSUE TITLE
Better parameters

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-generators-net#52]
Relates to: #46 

We need to come up with a more user friendly parameter structure to clearly separate generation of:

- [delivery models](https://github.com/Kentico/cloud-generators-net#how-to-use-for-delivery-sdk)
- [content management models](https://github.com/Kentico/cloud-generators-net#how-to-use-for-content-management-sdk)

We could e.g. introduce ["commands"](https://github.com/dotnet/corefxlab/tree/master/src/System.CommandLine#defining-commands).

@JanLenoch what you think would be the best approach?

**Comment by JanLenoch** [comment]
I'd go with System.CommandLine commands, even it is not RTM ATM.

**Comment by JanLenoch** [comment]
Fixed by #46 .
