### ISSUE TITLE
Should code be refactored to more separate the Delivery, CM API and common parts?

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/cloud-generators-net#53]
The current implementation is quite condensed in the [ClassCodeGenerator](https://github.com/Kentico/cloud-generators-net/blob/master/src/CloudModelGenerator/ClassCodeGenerator.cs) .

What are your opinions on refactoring the code to more cleanly separate the above three parts? Is it worth it at the moment?

**Comment by petrsvihlik** [comment]
Nice to have. Could you pls be more specific about what should be extracted and how/where?

**Comment by JanLenoch** [comment]
Originally, this question was placed by @huluvu21 and @sutrkiller who have implemented the current version. I'll try to get the details from them and do an in-depth review eventually (if guys don't have more specific opinions about how to refactor).

**Comment by JanLenoch** [comment]
No requests have been made to do the refactoring, apart from the original one.
