### ISSUE TITLE
Unhandled exception when using dotnet run

### ISSUE THREAD

**Issue by jancerman** [Kentico/cloud-generators-net#54]
### Brief bug description

When I try to run the generator using `dotnet run`, such as:

`dotnet run --projectid "975bf280-fd91-488c-994c-2f04416e5ee3"`
 
I get "Unhandled Exception: System.ArgumentException: The path is not of a legal form." and dotnet crashes.
 
If I add the `--outputdir` parameter:

`dotnet run --projectid "975bf280-fd91-488c-994c-2f04416e5ee3" --outputdir "C:\KC\demo\"`
 
I get "Unhandled Exception: System.ArgumentException: Illegal characters in path." 

Removing the backslash at the end fixes the problem and the generator works as intended.  
 
The precompiled executable does not have this problem. For example, running the latest exe (taken from https://github.com/Kentico/cloud-generators-net/releases/) directly without the `--outputdir` parameter works fine.

**Comment by JanLenoch** [comment]
@jancerman , could you please try to reproduce the issue now? If the issue still occurs, could you grab the stack trace? Thanks!

**Comment by jancerman** [comment]
@JanLenoch Tried it with the latest version on master branch. The original command (`dotnet run --projectid "975bf280-fd91-488c-994c-2f04416e5ee3"`) now works fine and results in the models being generated without an error.

Executing a command such as this `dotnet run --projectid "975bf280-fd91-488c-994c-2f04416e5ee3" --outputdir "C:\KC\demo\"` leads to the following error after which the program crashes:

```
Unhandled Exception: System.ArgumentException: Illegal characters in path.
   at System.IO.PathHelper.Normalize(String path, Boolean checkInvalidCharacters, Boolean expandShortPaths)
   at System.IO.Path.GetFullPath(String path)
   at CloudModelGenerator.CodeGenerator..ctor(IOptions`1 options) in C:\Users\JanC\Documents\cloud-generators-net\src\CloudModelGenerator\CodeGenerator.cs:line 27
   at CloudModelGenerator.Program.Execute(ArgumentSyntax argSyntax) in C:\Users\JanC\Documents\cloud-generators-net\src\CloudModelGenerator\Program.cs:line 76
   at CloudModelGenerator.Program.Main(String[] args) in C:\Users\JanC\Documents\cloud-generators-net\src\CloudModelGenerator\Program.cs:line 32`
```

**Comment by JanLenoch** [comment]
Caused by a "by-design" behavior of the .NET runtime. Before calling `System.CommandLine`, the runtime does an initial parsing of all arguments. When an argument value ends with a backslash character and double quotes (`\"`), the runtime understands that backslash as an escaping character and passes the quotes further through `System.CommandLine` to `Path.GetFullPath()`. Then, it throws for illegal characters in the path.

Found a suitable workaround.

**Comment by petrsvihlik** [comment]
An attempt has been made to fix this issue: https://github.com/Kentico/cloud-generators-net/pull/64
We have no resources to attend to it at the moment. We leave it to the community.
