### ISSUE TITLE
Duplicate code in model class

### ISSUE THREAD

**Issue by tkhodzhaev** [Kentico/cloud-generators-net#55]
Sometimes Generator produces unbuildable code. For example, please check the code on the screenshot below.

Here I have two content elements named 'Title' in my 'Article' content type, but one of them is inserted into a content snippet named 'Banner Page Content', wich is added to 'Article'.

So, when I generate models - I get duplicate field names, as you can see on the screenshot.

![image](https://user-images.githubusercontent.com/35305907/34787852-07bec66e-f639-11e7-939f-f53fa8574c05.png)

![image](https://user-images.githubusercontent.com/35305907/34788165-1131e0c2-f63a-11e7-9b03-84ac10858fa5.png)

![image](https://user-images.githubusercontent.com/35305907/34788172-1710c6b6-f63a-11e7-9b82-ffe1d8e68f9d.png)

**Comment by petrsvihlik** [comment]
hi @tkhodzhaev , thanks for submitting the issue. i don't see any other solution than to include codenames of content snippets/types into the names of properties. what do you think @ChristopherJennings , @JanLenoch , @Simply007 ? do we want to go that way?

**Comment by JanLenoch** [comment]
Hi @petrsvihlik , agreed. Running in.

**Comment by JanLenoch** [comment]
Hi @tkhodzhaev ,

Which version of the generator do you use? Could you try to reproduce the issue with the [latest release](https://github.com/Kentico/cloud-generators-net/releases/latest)?

There was a [bug](https://github.com/Kentico/cloud-generators-net/pull/59) in the process of generating the identifiers of codename constants. However, it behaved in a different way than what I could see in your screenshots.

If the issue prevails with the latest release of the generator, you can reach me over email to discuss all the details. I'll be happy to help more.

Thanks!

**Comment by tkhodzhaev** [comment]
Hello,

seems like it's fixed now, I can't reproduce it in latest version.


Thanks,
Tim

>Пятница, 26 января 2018, 18:00 +01:00 от Jan Lenoch <notifications@github.com>:
>
>Hi  @tkhodzhaev ,
>Which version of the generator do you use? Could you try to reproduce the issue with the  latest release ?
>There was a  bug in the process of generating the identifiers of codename constants. However, it behaved in a different way than what I could see in your screenshots.
>If the issue prevails with the latest release of the generator, you can reach me over email to discuss all the details. I'll be happy to help more.
>Thanks!
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


---

T. Kh.
