### ISSUE TITLE
Make custom type providers return content type codenames by CLR types

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-generators-net#61]
### Motivation

Currently, the generated custom type providers may only get `Type` by `string`. It should work also the other way around. This should help us reimplement https://github.com/Kentico/delivery-sdk-net/issues/79 . Here, we've implemented a `ContentTypeExtractor` that allows the developer to entirely omit the `EqualsFilter` in the following case:

    var response = await DeliveryClient.GetItemsAsync<Article>(
        new EqualsFilter("system.type", "article"),
    );

### Howto

The [TypeProviderCodeGenerator](https://github.com/Kentico/cloud-generators-net/blob/master/src/CloudModelGenerator/TypeProviderCodeGenerator.cs) should not only generate the `GetType` method but also a new `GetCodename` one. We should generate a dictionary of `<Type, string>` that would be used by the `GetCodename` method.

- [x] But first, we'll need to enhance [ICodeFirstTypeProvider](https://github.com/Kentico/delivery-sdk-net/blob/master/KenticoCloud.Delivery/CodeFirst/ICodeFirstTypeProvider.cs) via https://github.com/Kentico/delivery-sdk-net/issues/101 .

Tip: Create a NuGet package of https://github.com/Kentico/delivery-sdk-net locally, so that it contains the latest changes of the `ICodeFirstTypeProvider` interface.

### Deployment
Release together with https://github.com/Kentico/delivery-sdk-net/milestone/8
- release notes of both packages should contain a note about the compatibility

**Comment by JanLenoch** [comment]
Blocked by https://github.com/Kentico/delivery-sdk-net/issues/101 .

**Comment by petrsvihlik** [comment]
fixed in #75
