### ISSUE TITLE
Enhance readme

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-generators-net#65]
- [ ] describe in a few words, when it's better to use [structured](https://github.com/Kentico/delivery-sdk-net/wiki/Structured-Rich-text-rendering) and [string-based](https://github.com/Kentico/delivery-sdk-net/wiki/String-based-rendering-of-modular-content-items-in-Rich-text). i suggest we put a simple page describing the use-cases to https://github.com/Kentico/delivery-sdk-net/wiki and just link it from generators' readme (in the parameter description)

**Comment by JanLenoch** [comment]
Filed under https://github.com/Kentico/delivery-sdk-net/issues/122
