### ISSUE TITLE
Make CustomTypeProvider more bulletproof

### ISSUE THREAD

**Issue by micheltol** [Kentico/cloud-generators-net#67]
### Brief bug description

When a new content type is added to KC and a new item of that type is retrieved via Delivery API (either directly or as a modular item), such retrieval fails because of the type provider returning `null` as [the default `System.Type`](https://github.com/Kentico/cloud-boilerplate-net/blob/master/src/content/CloudBoilerplateNet/Models/ContentTypes/CustomTypeProvider.cs#L39) of such unknown content type, unless the new type provider (and models) are generated.

### Original bug description

Hi,

I am currently facing the situation where we are frequently updating our models in KC but the source code is not beging updated as much. Reason: multiple work in progress stories, multiple developers etc. 

We are frequently running into the following issue:
When we are updating a 'root' content type referencing a new content type via modular content reference our C# web application will throw an exception because the `CustomTypeProvider` is returning a `NULL` for unknown content types.

Our workaround is when we generate our models via cloud-generators-net we are changing manually the CustomTypeProvider to return as a default value `typeof(object)` instead of null. This change will keep our code work without any side-effects.

What is your take on this? I can send a PR with the changed source code.

### Repro steps

1. Create a content type in KC
1. Create a content item of that type
1. Do not generate new type provider
1. Either retrieve all items
1. or add that item to another item as a modular item, and retrieve the parent item

**Comment by petrsvihlik** [comment]
Hi @micheltol , thank you for the suggestion! 

Can you please share the code where returning `null` from `CustomTypeProvider` is causing issues?

**Comment by LiryChen** [comment]
Hey, I am a first-timer looking for open source tasks to start contributing to the community. I found this issue pretty interesting. Could I claim it? Is there anyone I can reach out to when I need help to understand the code and the issue?

**Comment by micheltol** [comment]
@lirychen you could contact me for understanding the issue.

@petrsvihlik I just realized I didn't respond to your question. Is the question still relevant?

**Comment by petrsvihlik** [comment]
Hi @micheltol, I just had another look and understood the issue :)
I think behavior of the CustomTypeProvider is ok..."if type is not found return null". 

What might be wrong/impractical is the null check in the [Delivery SDK's](https://github.com/Kentico/delivery-sdk-net) `CodeFirstModelProvider`. The code in question is [here](https://github.com/Kentico/delivery-sdk-net/blob/7a368f54f462a8d2609a17cf2569d632bd7be14d/KenticoCloud.Delivery/CodeFirst/CodeFirstModelProvider.cs#L78). 

Would you agree? If yes, I'll move the issue [there](https://github.com/Kentico/delivery-sdk-net) and we can continue the discussion there.

@LiryChen I'll be more than happy to get you started. I invited you to both repos. If you accept the invitation I'll be able to assign the issue to you. In the meantime, we'll decide where the fix needs to take place. Once decided, I'll tell you what's needed for the fix.

**Comment by micheltol** [comment]
@petrsvihlik agreed.

**Comment by petrsvihlik** [comment]
To be continued in https://github.com/Kentico/delivery-sdk-net/issues/126

**Comment by petrsvihlik** [comment]
@micheltol  would you like to express your opinion about how it should be solved in https://github.com/Kentico/delivery-sdk-net/issues/126 ? thanks!
