### ISSUE TITLE
Unit tests - fine-tuning

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-generators-net#7]
- [x] use the official sample project - Project ID: 975bf280-fd91-488c-994c-2f04416e5ee3
- [x] mock the responses coming from the SDK so that the tests are not dependent on any specific project in Kentico Cloud (use Moq or FakeItEasy) - here's how: https://github.com/Kentico/delivery-sdk-net/wiki/Faking-responses
- [x] fix whitespaces - https://ci.appveyor.com/project/kentico/cloud-generators-net/build/tests

**Comment by ondrejsevcik** [comment]
I don't have access to that project so it's up to you 😋

**Comment by petrsvihlik** [comment]
done by @kashifsoofi in #34
