### ISSUE TITLE
Change generated type for modular content

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/cloud-generators-net#8]
https://github.com/Kentico/delivery-sdk-net/wiki/Working-with-Strongly-Typed-Models-(aka-Code-First-Approach)

We should probably start generating modular content fields as:

IEnumerable<object> instead of IEnumerable<ContentItem>

This way it'll be consistent and we won't mix the strong and weak type approaches.

**Comment by ondrejsevcik** [comment]
IEnumerable instead of IEnumerable <- Isn't there a typo? 🤔

**Comment by petrsvihlik** [comment]
lol, sorry :) github didn't render the markdown correctly
`IEnumerable<object> instead of IEnumerable<ContentItem>`
